# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_services import roop_pb2 as roop__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in roop_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RoopStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.faceSwap = channel.unary_unary(
                '/roop.Roop/faceSwap',
                request_serializer=roop__pb2.RoopInputMsg.SerializeToString,
                response_deserializer=roop__pb2.RoopResponse.FromString,
                _registered_method=True)
        self.faceEnhancement = channel.unary_unary(
                '/roop.Roop/faceEnhancement',
                request_serializer=roop__pb2.RoopInputMsg.SerializeToString,
                response_deserializer=roop__pb2.RoopResponse.FromString,
                _registered_method=True)


class RoopServicer(object):
    """Missing associated documentation comment in .proto file."""

    def faceSwap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def faceEnhancement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoopServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'faceSwap': grpc.unary_unary_rpc_method_handler(
                    servicer.faceSwap,
                    request_deserializer=roop__pb2.RoopInputMsg.FromString,
                    response_serializer=roop__pb2.RoopResponse.SerializeToString,
            ),
            'faceEnhancement': grpc.unary_unary_rpc_method_handler(
                    servicer.faceEnhancement,
                    request_deserializer=roop__pb2.RoopInputMsg.FromString,
                    response_serializer=roop__pb2.RoopResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'roop.Roop', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('roop.Roop', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Roop(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def faceSwap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/roop.Roop/faceSwap',
            roop__pb2.RoopInputMsg.SerializeToString,
            roop__pb2.RoopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def faceEnhancement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/roop.Roop/faceEnhancement',
            roop__pb2.RoopInputMsg.SerializeToString,
            roop__pb2.RoopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
